
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etl
      POSTGRES_USER: postgres
    ports: ["5433:5433"]
    volumes:
      - ./infra/sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d etl"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]
    volumes:
      - ./app:/app/app
      - ./data:/data
      - ./tests:/tests
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 

